export const jobs = [
  {
    id: 1,
    title: "Senior Java Backend Developer",
    description:
      "We are looking for a skilled backend developer to build scalable microservices using Spring Boot and Kafka.",
    requirements:
      "5+ years experience in Java, Spring Boot, Microservices, Docker, Kubernetes, Kafka",
    responsibilities:
      "Design APIs, build microservices, optimize performance, collaborate with frontend team",
    benefits: "Health insurance, flexible working hours, remote work options",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 1,
      name: "Software Development",
      slug: "software-development",
      description:
        "Jobs related to software engineering, backend, frontend, and full-stack development.",
      iconUrl: "https://cdn.zosh.com/icons/software-development.png",
      active: true,
      createdAt: "2026-02-28T22:44:31.616396",
    },
    skills: [
      {
        id: 1,
        name: "Spring Boot",
        slug: "spring-boot",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 3,
        name: "Fast API",
        slug: "fast-api",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 2,
        name: "React",
        slug: "react",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 5,
        name: "AI/ML",
        slug: "aiml",
      },
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
    ],
    address: "Rajkot IT Park",
    city: "Rajkot",
    state: "Gujarat",
    country: "India",
    zipCode: "360001",
    minSalary: 800000,
    maxSalary: 1800000,
    currency: "INR",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 3,
    applicationDeadline: "2026-03-31",
    expiresAt: "2026-04-15",
    active: true,
    viewCount: 6,
    applicationCount: 0,
    createdAt: "2026-02-28T23:15:37.736102",
    updatedAt: "2026-04-09T14:58:59.236868",
    publishedAt: "2026-03-02T17:41:57.930648",
  },
  {
    id: 3,
    title: "Frontend React Developer",
    description:
      "Join our product team to build beautiful user interfaces for our SaaS platform...",
    requirements: "5+ years of React, TypeScript, Redux, modern CSS frameworks",
    responsibilities:
      "Develop new features, optimize performance, collaborate with designers, maintain component library",
    benefits:
      "Flexible hours, learning budget, equity options, home office stipend",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 3,
      name: "Healthcare",
      slug: "healthcare",
      description: "Medical and healthcare positions",
      iconUrl: "https://example.com/icons/healthcare.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.295085",
    },
    skills: [
      {
        id: 4,
        name: "Java",
        slug: "java",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 64,
        name: "Conflict Resolution",
        slug: "conflict-resolution",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 3,
        name: "Fast API",
        slug: "fast-api",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 12,
        name: "Swift",
        slug: "swift",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
    ],
    tags: [
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
      {
        id: 57,
        name: "Equity",
        slug: "equity",
      },
      {
        id: 4,
        name: "Microservices",
        slug: "microservices",
      },
    ],
    address: "456 Innovation Ave",
    city: "Austin",
    state: "TX",
    country: "USA",
    zipCode: "78701",
    minSalary: 110000,
    maxSalary: 145000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: false,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-11-15",
    expiresAt: "2024-12-15",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.418109",
    updatedAt: "2026-03-02T19:01:30.66264",
    publishedAt: "2026-03-02T19:01:30.659561",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    description:
      "Looking for a DevOps engineer to manage and optimize our cloud infrastructure on AWS...",
    requirements:
      "AWS, Kubernetes, Terraform, CI/CD pipelines, Linux administration",
    responsibilities:
      "Maintain and improve infrastructure, automate deployments, implement monitoring solutions",
    benefits:
      "Certification reimbursement, home office stipend, flexible schedule",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 8,
      name: "Human Resources",
      slug: "human-resources",
      description: "HR and talent acquisition positions",
      iconUrl: "https://example.com/icons/hr.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.320802",
    },
    skills: [
      {
        id: 39,
        name: "Alibaba Cloud",
        slug: "alibaba-cloud",
        category: "CLOUD_PLATFORM",
        active: true,
      },
      {
        id: 44,
        name: "GitLab CI",
        slug: "gitlab-ci",
        category: "DEVOPS",
        active: true,
      },
      {
        id: 40,
        name: "Docker",
        slug: "docker",
        category: "DEVOPS",
        active: true,
      },
      {
        id: 31,
        name: "SQLite",
        slug: "sqlite",
        category: "DATABASE",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 15,
        name: "Part Time",
        slug: "part-time",
      },
      {
        id: 52,
        name: "Work Life Balance",
        slug: "work-life-balance",
      },
    ],
    address: "789 Cloud Road",
    city: "Seattle",
    state: "WA",
    country: "USA",
    zipCode: "98101",
    minSalary: 130000,
    maxSalary: 165000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 1,
    applicationDeadline: "2024-10-30",
    expiresAt: "2024-11-30",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.450732",
    updatedAt: "2026-03-02T19:01:36.23217",
    publishedAt: "2026-03-02T19:01:36.228784",
  },
  {
    id: 11,
    title: "Sales Development Representative",
    description:
      "Generate leads and qualify prospects for our B2B SaaS platform...",
    requirements:
      "Sales experience, excellent communication, CRM knowledge, cold calling",
    responsibilities:
      "Outbound prospecting, qualify leads, schedule demos, maintain pipeline in Salesforce",
    benefits:
      "Commission structure, career growth, team events, health benefits",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 36,
      name: "Account Executive",
      slug: "account-executive",
      description: "Enterprise and mid-market sales",
      iconUrl: "https://example.com/icons/ae.png",
      active: true,
      parentId: 6,
      parentName: "Marketing",
      createdAt: "2026-03-02T18:08:23.46006",
    },
    skills: [
      {
        id: 64,
        name: "Conflict Resolution",
        slug: "conflict-resolution",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 68,
        name: "Trello",
        slug: "trello",
        category: "TOOL",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 5,
        name: "AI/ML",
        slug: "aiml",
      },
      {
        id: 30,
        name: "Government Job",
        slug: "government-job",
      },
      {
        id: 53,
        name: "Wellness Program",
        slug: "wellness-program",
      },
      {
        id: 29,
        name: "Security Clearance",
        slug: "security-clearance",
      },
    ],
    address: "808 Sales Blvd",
    city: "Atlanta",
    state: "GA",
    country: "USA",
    zipCode: "30303",
    minSalary: 50000,
    maxSalary: 70000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "ON_SITE",
    experienceLevel: "ENTRY_LEVEL",
    status: "OPEN",
    openings: 5,
    applicationDeadline: "2024-10-01",
    expiresAt: "2024-11-01",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.704763",
    updatedAt: "2026-03-02T19:01:47.239288",
    publishedAt: "2026-03-02T19:01:47.236164",
  },
  {
    id: 10,
    title: "Android Developer",
    description:
      "Create innovative Android applications for our growing user base...",
    requirements:
      "Kotlin, Android SDK, Material Design, Firebase, Jetpack Compose",
    responsibilities:
      "Build Android features, optimize for different devices, play store deployment, mentor juniors",
    benefits:
      "Android devices, conference tickets, flexible schedule, learning budget",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 6,
      name: "Marketing",
      slug: "marketing",
      description: "Marketing and advertising positions",
      iconUrl: "https://example.com/icons/marketing.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.310277",
    },
    skills: [
      {
        id: 8,
        name: "C#",
        slug: "c",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 10,
        name: "Go",
        slug: "go",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 14,
        name: "Angular",
        slug: "angular",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 12,
        name: "Swift",
        slug: "swift",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
      {
        id: 57,
        name: "Equity",
        slug: "equity",
      },
      {
        id: 52,
        name: "Work Life Balance",
        slug: "work-life-balance",
      },
    ],
    address: "707 Android Avenue",
    city: "Mountain View",
    state: "CA",
    country: "USA",
    zipCode: "94040",
    minSalary: 110000,
    maxSalary: 145000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-11-20",
    expiresAt: "2024-12-20",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.674048",
    updatedAt: "2026-03-02T19:01:50.504463",
    publishedAt: "2026-03-02T19:01:50.501473",
  },
  {
    id: 9,
    title: "iOS Developer",
    description:
      "Build amazing iOS applications for our millions of users worldwide...",
    requirements:
      "Swift, iOS SDK, Core Data, UI/UX principles, Combine framework",
    responsibilities:
      "Develop iOS features, optimize performance, app store submissions, code reviews",
    benefits:
      "Latest Apple equipment, app store revenue share, health benefits, conference tickets",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 5,
      name: "Education",
      slug: "education",
      description: "Teaching and academic roles",
      iconUrl: "https://example.com/icons/education.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.305821",
    },
    skills: [
      {
        id: 10,
        name: "Go",
        slug: "go",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 13,
        name: "Kotlin",
        slug: "kotlin",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 9,
        name: "C++",
        slug: "c-1",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 12,
        name: "Swift",
        slug: "swift",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
      {
        id: 57,
        name: "Equity",
        slug: "equity",
      },
      {
        id: 52,
        name: "Work Life Balance",
        slug: "work-life-balance",
      },
    ],
    address: "606 Apple Way",
    city: "San Jose",
    state: "CA",
    country: "USA",
    zipCode: "95110",
    minSalary: 115000,
    maxSalary: 150000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-12-01",
    expiresAt: "2025-01-01",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.644948",
    updatedAt: "2026-03-02T19:01:54.200982",
    publishedAt: "2026-03-02T19:01:54.197696",
  },
  {
    id: 8,
    title: "QA Automation Engineer",
    description:
      "Ensure quality through automated testing frameworks for our e-commerce platform...",
    requirements: "Selenium, Java/Python, CI/CD, test frameworks, API testing",
    responsibilities:
      "Write automated tests, maintain test suites, bug tracking, integrate with CI/CD",
    benefits:
      "Learning opportunities, team outings, health benefits, certification support",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 20,
      name: "Science",
      slug: "science",
      description: "Scientific research and laboratory roles",
      iconUrl: "https://example.com/icons/science.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.376605",
    },
    skills: [
      {
        id: 64,
        name: "Conflict Resolution",
        slug: "conflict-resolution",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 22,
        name: "MySQL",
        slug: "mysql",
        category: "DATABASE",
        active: true,
      },
      {
        id: 1,
        name: "Spring Boot",
        slug: "spring-boot",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 2,
        name: "React",
        slug: "react",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 63,
        name: "Parental Leave",
        slug: "parental-leave",
      },
      {
        id: 52,
        name: "Work Life Balance",
        slug: "work-life-balance",
      },
    ],
    address: "404 Quality Lane",
    city: "Denver",
    state: "CO",
    country: "USA",
    zipCode: "80202",
    minSalary: 85000,
    maxSalary: 110000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: false,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-10-15",
    expiresAt: "2024-11-15",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.590514",
    updatedAt: "2026-03-02T19:01:57.930728",
    publishedAt: "2026-03-02T19:01:57.928724",
  },
  {
    id: 6,
    title: "Product Manager",
    description:
      "Lead product strategy for our flagship SaaS product in the fintech space...",
    requirements:
      "5+ years PM experience, technical background, agile methodologies, fintech experience",
    responsibilities:
      "Define product roadmap, work with engineering, stakeholder management, market research",
    benefits:
      "Leadership training, performance bonuses, stock options, flexible PTO",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 23,
      name: "Telecommunications",
      slug: "telecommunications",
      description: "Telecom and network infrastructure",
      iconUrl: "https://example.com/icons/telecom.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.390492",
    },
    skills: [
      {
        id: 85,
        name: "RESTful APIs",
        slug: "restful-apis",
        category: "OTHER",
        active: true,
      },
      {
        id: 87,
        name: "Event-Driven Architecture",
        slug: "event-driven-architecture",
        category: "OTHER",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 34,
        name: "Multinational",
        slug: "multinational",
      },
      {
        id: 31,
        name: "Nonprofit",
        slug: "nonprofit",
      },
      {
        id: 32,
        name: "Startup",
        slug: "startup",
      },
      {
        id: 52,
        name: "Work Life Balance",
        slug: "work-life-balance",
      },
    ],
    address: "202 Market Street",
    city: "Chicago",
    state: "IL",
    country: "USA",
    zipCode: "60601",
    minSalary: 125000,
    maxSalary: 160000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "LEAD",
    status: "OPEN",
    openings: 1,
    applicationDeadline: "2024-12-15",
    expiresAt: "2025-01-15",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.520306",
    updatedAt: "2026-03-02T19:02:02.670243",
    publishedAt: "2026-03-02T19:02:02.66624",
  },
  {
    id: 7,
    title: "Data Scientist",
    description:
      "Join our data team to build ML models and derive insights from large datasets...",
    requirements:
      "Python, SQL, Machine Learning, TensorFlow, PyTorch, Statistics",
    responsibilities:
      "Build predictive models, analyze data, present findings, collaborate with engineering",
    benefits:
      "Research publications, conference attendance, flexible schedule, learning budget",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 11,
      name: "Construction",
      slug: "construction",
      description: "Construction and trades positions",
      iconUrl: "https://example.com/icons/construction.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.334962",
    },
    skills: [
      {
        id: 22,
        name: "MySQL",
        slug: "mysql",
        category: "DATABASE",
        active: true,
      },
      {
        id: 87,
        name: "Event-Driven Architecture",
        slug: "event-driven-architecture",
        category: "OTHER",
        active: true,
      },
      {
        id: 21,
        name: "Express.js",
        slug: "expressjs",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 2,
        name: "React",
        slug: "react",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 63,
        name: "Parental Leave",
        slug: "parental-leave",
      },
    ],
    address: "303 Data Drive",
    city: "Boston",
    state: "MA",
    country: "USA",
    zipCode: "02110",
    minSalary: 135000,
    maxSalary: 170000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-11-30",
    expiresAt: "2024-12-31",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.557811",
    updatedAt: "2026-03-02T19:02:06.585445",
    publishedAt: "2026-03-02T19:02:06.583305",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    description:
      "Creative designer needed for our growing design team to craft exceptional user experiences...",
    requirements: "Figma, Adobe XD, user research, prototyping, design systems",
    responsibilities:
      "Create wireframes, conduct user testing, maintain design systems, collaborate with product team",
    benefits:
      "Creative freedom, design conferences, wellness benefits, flexible hours",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 26,
      name: "Nonprofit",
      slug: "nonprofit",
      description: "Nonprofit and charity organizations",
      iconUrl: "https://example.com/icons/nonprofit.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.404753",
    },
    skills: [
      {
        id: 50,
        name: "Adobe Photoshop",
        slug: "adobe-photoshop",
        category: "DESIGN",
        active: true,
      },
      {
        id: 51,
        name: "Adobe Illustrator",
        slug: "adobe-illustrator",
        category: "DESIGN",
        active: true,
      },
      {
        id: 48,
        name: "Grafana",
        slug: "grafana",
        category: "DEVOPS",
        active: true,
      },
      {
        id: 49,
        name: "Figma",
        slug: "figma",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 18,
        name: "Permanent",
        slug: "permanent",
      },
      {
        id: 93,
        name: "Best Place to Work",
        slug: "best-place-to-work",
      },
      {
        id: 4,
        name: "Microservices",
        slug: "microservices",
      },
    ],
    address: "101 Design Blvd",
    city: "New York",
    state: "NY",
    country: "USA",
    zipCode: "10001",
    minSalary: 90000,
    maxSalary: 120000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: false,
    jobType: "FULL_TIME",
    workMode: "ON_SITE",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2026-06-26",
    expiresAt: "2026-10-29",
    active: true,
    viewCount: 2,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.488113",
    updatedAt: "2026-04-10T18:48:26.068896",
    publishedAt: "2026-03-02T19:01:40.8456",
  },
  {
    id: 22,
    title: "Machine Learning Engineer",
    description:
      "Build and deploy ML models to production for our recommendation engine...",
    requirements:
      "Python, TensorFlow, PyTorch, ML pipelines, model deployment, MLOps",
    responsibilities:
      "Develop ML models, optimize algorithms, deploy to production, monitor performance",
    benefits: "Research time, conference budget, flexible hours, stock options",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 12,
      name: "Manufacturing",
      slug: "manufacturing",
      description: "Manufacturing and production roles",
      iconUrl: "https://example.com/icons/manufacturing.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.340007",
    },
    skills: [
      {
        id: 22,
        name: "MySQL",
        slug: "mysql",
        category: "DATABASE",
        active: true,
      },
      {
        id: 87,
        name: "Event-Driven Architecture",
        slug: "event-driven-architecture",
        category: "OTHER",
        active: true,
      },
      {
        id: 21,
        name: "Express.js",
        slug: "expressjs",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 2,
        name: "React",
        slug: "react",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 63,
        name: "Parental Leave",
        slug: "parental-leave",
      },
    ],
    address: "1919 ML Boulevard",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    zipCode: "94105",
    minSalary: 145000,
    maxSalary: 185000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-12-15",
    expiresAt: "2025-01-15",
    active: true,
    viewCount: 31,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.10471",
    updatedAt: "2026-04-10T14:47:58.839067",
    publishedAt: "2026-03-02T19:02:58.76073",
  },
  {
    id: 29,
    title: "Data Engineer",
    description:
      "Build and maintain data pipelines for our analytics and machine learning teams...",
    requirements: "Python, SQL, Spark, Airflow, data warehousing, ETL/ELT",
    responsibilities:
      "Design data pipelines, optimize data processing, ensure data quality",
    benefits: "Learning budget, conference attendance, flexible hours, equity",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 13,
      name: "Retail",
      slug: "retail",
      description: "Retail and customer service positions",
      iconUrl: "https://example.com/icons/retail.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.344008",
    },
    skills: [
      {
        id: 18,
        name: "Ruby on Rails",
        slug: "ruby-on-rails",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 17,
        name: "Flask",
        slug: "flask",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 24,
        name: "MongoDB",
        slug: "mongodb",
        category: "DATABASE",
        active: true,
      },
      {
        id: 2,
        name: "React",
        slug: "react",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 63,
        name: "Parental Leave",
        slug: "parental-leave",
      },
    ],
    address: "2626 Pipeline Road",
    city: "Chicago",
    state: "IL",
    country: "USA",
    zipCode: "60601",
    minSalary: 125000,
    maxSalary: 160000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-12-10",
    expiresAt: "2025-01-10",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.341784",
    updatedAt: "2026-03-02T19:02:44.848538",
    publishedAt: "2026-03-02T19:02:44.84118",
  },
  {
    id: 31,
    title: "UX Researcher",
    description: "Conduct user research to inform product design decisions...",
    requirements:
      "User research methods, usability testing, data analysis, presentation skills",
    responsibilities:
      "Plan research studies, conduct interviews, synthesize findings, present insights",
    benefits:
      "Research budget, conference attendance, flexible hours, remote work",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 27,
      name: "IT Support",
      slug: "it-support",
      description: "Technical support and help desk positions",
      iconUrl: "https://example.com/icons/itsupport.png",
      active: true,
      parentId: 1,
      parentName: "Software Development",
      createdAt: "2026-03-02T18:08:23.415249",
    },
    skills: [
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 48,
        name: "Grafana",
        slug: "grafana",
        category: "DEVOPS",
        active: true,
      },
      {
        id: 49,
        name: "Figma",
        slug: "figma",
        category: "DESIGN",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 18,
        name: "Permanent",
        slug: "permanent",
      },
      {
        id: 93,
        name: "Best Place to Work",
        slug: "best-place-to-work",
      },
      {
        id: 4,
        name: "Microservices",
        slug: "microservices",
      },
    ],
    address: "2828 Research Park",
    city: "Boston",
    state: "MA",
    country: "USA",
    zipCode: "02110",
    minSalary: 95000,
    maxSalary: 125000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 1,
    applicationDeadline: "2024-11-05",
    expiresAt: "2024-12-05",
    active: true,
    viewCount: 4,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.400064",
    updatedAt: "2026-04-08T18:52:44.494321",
    publishedAt: "2026-03-02T19:02:48.895775",
  },
  {
    id: 2,
    title: "Senior Java Developer",
    description:
      "We are looking for an experienced Java developer to join our core backend team building scalable microservices...",
    requirements:
      "8+ years of Java experience, Spring Boot, Microservices, Distributed Systems",
    responsibilities:
      "Design and develop scalable backend services, conduct code reviews, mentor junior developers",
    benefits:
      "Health insurance, 401k matching, remote work allowance, annual bonus",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 1,
      name: "Software Development",
      slug: "software-development",
      description:
        "Jobs related to software engineering, backend, frontend, and full-stack development.",
      iconUrl: "https://cdn.zosh.com/icons/software-development.png",
      active: true,
      createdAt: "2026-02-28T22:44:31.616396",
    },
    skills: [
      {
        id: 39,
        name: "Alibaba Cloud",
        slug: "alibaba-cloud",
        category: "CLOUD_PLATFORM",
        active: true,
      },
      {
        id: 11,
        name: "Rust",
        slug: "rust",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 86,
        name: "GraphQL",
        slug: "graphql",
        category: "OTHER",
        active: true,
      },
      {
        id: 1,
        name: "Spring Boot",
        slug: "spring-boot",
        category: "FRAMEWORK",
        active: true,
      },
    ],
    tags: [
      {
        id: 50,
        name: "High Growth",
        slug: "high-growth",
      },
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 53,
        name: "Wellness Program",
        slug: "wellness-program",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
    ],
    address: "123 Tech Street",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    zipCode: "94105",
    minSalary: 140000,
    maxSalary: 180000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "SENIOR_LEVEL",
    status: "OPEN",
    openings: 3,
    applicationDeadline: "2024-12-31",
    expiresAt: "2025-01-31",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:49.351848",
    updatedAt: "2026-03-02T19:01:26.783307",
    publishedAt: "2026-03-02T19:01:26.779312",
  },
  {
    id: 28,
    title: "React Native Developer",
    description:
      "Build cross-platform mobile applications using React Native...",
    requirements:
      "React Native, JavaScript/TypeScript, Redux, mobile UI/UX, API integration",
    responsibilities:
      "Develop mobile features, optimize performance, app store deployments",
    benefits: "Latest devices, flexible hours, learning budget, remote work",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 7,
      name: "Sales",
      slug: "sales",
      description: "Sales and business development roles",
      iconUrl: "https://example.com/icons/sales.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.315462",
    },
    skills: [
      {
        id: 4,
        name: "Java",
        slug: "java",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 3,
        name: "Fast API",
        slug: "fast-api",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 12,
        name: "Swift",
        slug: "swift",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 7,
        name: "TypeScript",
        slug: "typescript",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
    ],
    tags: [
      {
        id: 1,
        name: "urgent-hiring",
        slug: "urgent-hiring",
      },
      {
        id: 3,
        name: "Fresher Friendly",
        slug: "fresher-friendly",
      },
      {
        id: 2,
        name: "visa-sponsored",
        slug: "visa-sponsored",
      },
      {
        id: 57,
        name: "Equity",
        slug: "equity",
      },
    ],
    address: "2525 Mobile Lane",
    city: "San Diego",
    state: "CA",
    country: "USA",
    zipCode: "92101",
    minSalary: 105000,
    maxSalary: 140000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "REMOTE",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-11-20",
    expiresAt: "2024-12-20",
    active: true,
    viewCount: 21,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.309903",
    updatedAt: "2026-04-10T14:00:41.461471",
    publishedAt: "2026-03-02T19:02:53.641525",
  },
  {
    id: 46,
    title: "Compliance Officer",
    description:
      "Ensure company compliance with regulations and industry standards...",
    requirements:
      "Compliance, risk management, regulatory knowledge, auditing, attention to detail",
    responsibilities:
      "Monitor compliance, conduct audits, update policies, employee training",
    benefits:
      "Professional development, flexible hours, health benefits, bonus",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 48,
      name: "Store Management",
      slug: "store-management",
      description: "Retail store management",
      iconUrl: "https://example.com/icons/store.png",
      active: true,
      parentId: 12,
      parentName: "Manufacturing",
      createdAt: "2026-03-02T18:08:23.509521",
    },
    skills: [
      {
        id: 57,
        name: "Communication",
        slug: "communication",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 62,
        name: "Leadership",
        slug: "leadership",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 25,
        name: "Rotating Shift",
        slug: "rotating-shift",
      },
      {
        id: 41,
        name: "Individual Contributor",
        slug: "individual-contributor",
      },
      {
        id: 42,
        name: "IC Role",
        slug: "ic-role",
      },
      {
        id: 46,
        name: "Customer Facing",
        slug: "customer-facing",
      },
    ],
    address: "4343 Compliance Court",
    city: "Washington",
    state: "DC",
    country: "USA",
    zipCode: "20001",
    minSalary: 75000,
    maxSalary: 105000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: false,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 1,
    applicationDeadline: "2024-10-30",
    expiresAt: "2024-11-30",
    active: true,
    viewCount: 9,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.857068",
    updatedAt: "2026-04-08T18:26:24.239564",
    publishedAt: "2026-03-02T19:02:22.83395",
  },
  {
    id: 30,
    title: "Accountant",
    description:
      "Manage financial records, accounts payable/receivable, and month-end closing...",
    requirements:
      "Accounting degree, GAAP knowledge, Excel, QuickBooks, attention to detail",
    responsibilities:
      "Process invoices, reconcile accounts, prepare financial statements, tax preparation",
    benefits: "CPA support, flexible hours, health benefits, 401k match",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 45,
      name: "Electrical",
      slug: "electrical",
      description: "Electrical installation and repair",
      iconUrl: "https://example.com/icons/electrical.png",
      active: true,
      parentId: 10,
      parentName: "Operations",
      createdAt: "2026-03-02T18:08:23.498121",
    },
    skills: [
      {
        id: 61,
        name: "Time Management",
        slug: "time-management",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 64,
        name: "Conflict Resolution",
        slug: "conflict-resolution",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 50,
        name: "High Growth",
        slug: "high-growth",
      },
      {
        id: 53,
        name: "Wellness Program",
        slug: "wellness-program",
      },
      {
        id: 42,
        name: "IC Role",
        slug: "ic-role",
      },
      {
        id: 29,
        name: "Security Clearance",
        slug: "security-clearance",
      },
    ],
    address: "2722 Accounting Street",
    city: "Columbus",
    state: "OH",
    country: "USA",
    zipCode: "43215",
    minSalary: 55000,
    maxSalary: 75000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: false,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "ON_SITE",
    experienceLevel: "JUNIOR",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-10-15",
    expiresAt: "2024-11-15",
    active: true,
    viewCount: 0,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.369923",
    updatedAt: "2026-03-02T19:02:40.767826",
    publishedAt: "2026-03-02T19:02:40.762827",
  },
  {
    id: 49,
    title: "Junior Web Developer",
    description:
      "Kickstart your career as a web developer working on exciting projects...",
    requirements: "HTML, CSS, JavaScript, React basics, willingness to learn",
    responsibilities:
      "Assist in development, fix bugs, learn from senior developers, write clean code",
    benefits: "Mentorship, learning budget, flexible hours, health benefits",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 3,
      name: "Healthcare",
      slug: "healthcare",
      description: "Medical and healthcare positions",
      iconUrl: "https://example.com/icons/healthcare.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.295085",
    },
    skills: [
      {
        id: 4,
        name: "Java",
        slug: "java",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
      {
        id: 64,
        name: "Conflict Resolution",
        slug: "conflict-resolution",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 3,
        name: "Fast API",
        slug: "fast-api",
        category: "FRAMEWORK",
        active: true,
      },
      {
        id: 12,
        name: "Swift",
        slug: "swift",
        category: "PROGRAMMING_LANGUAGE",
        active: true,
      },
    ],
    tags: [
      {
        id: 5,
        name: "AI/ML",
        slug: "aiml",
      },
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 41,
        name: "Individual Contributor",
        slug: "individual-contributor",
      },
      {
        id: 66,
        name: "Sabbatical",
        slug: "sabbatical",
      },
    ],
    address: "4646 Junior Lane",
    city: "Austin",
    state: "TX",
    country: "USA",
    zipCode: "78701",
    minSalary: 60000,
    maxSalary: 75000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: false,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "JUNIOR",
    status: "OPEN",
    openings: 3,
    applicationDeadline: "2024-11-30",
    expiresAt: "2024-12-30",
    active: true,
    viewCount: 114,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.931545",
    updatedAt: "2026-04-26T08:55:39.023782",
    publishedAt: "2026-03-02T19:02:13.081181",
  },
  {
    id: 48,
    title: "Brand Manager",
    description:
      "Develop and execute brand strategy to strengthen market position...",
    requirements:
      "Brand management, marketing strategy, market research, creative direction",
    responsibilities:
      "Define brand identity, manage campaigns, analyze market trends",
    benefits: "Creative role, marketing budget, conferences, performance bonus",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 30,
      name: "Investment Banking",
      slug: "investment-banking",
      description: "Investment banking and trading roles",
      iconUrl: "https://example.com/icons/investment.png",
      active: true,
      parentId: 3,
      parentName: "Healthcare",
      createdAt: "2026-03-02T18:08:23.430153",
    },
    skills: [
      {
        id: 57,
        name: "Communication",
        slug: "communication",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 59,
        name: "Problem Solving",
        slug: "problem-solving",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 30,
        name: "Government Job",
        slug: "government-job",
      },
      {
        id: 53,
        name: "Wellness Program",
        slug: "wellness-program",
      },
      {
        id: 32,
        name: "Startup",
        slug: "startup",
      },
      {
        id: 29,
        name: "Security Clearance",
        slug: "security-clearance",
      },
    ],
    address: "4545 Brand Blvd",
    city: "New York",
    state: "NY",
    country: "USA",
    zipCode: "10001",
    minSalary: 95000,
    maxSalary: 130000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "LEAD",
    status: "OPEN",
    openings: 1,
    applicationDeadline: "2024-12-10",
    expiresAt: "2025-01-10",
    active: true,
    viewCount: 40,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.907774",
    updatedAt: "2026-04-10T17:57:09.78222",
    publishedAt: "2026-03-02T19:02:19.381712",
  },
  {
    id: 44,
    title: "Technical Trainer",
    description:
      "Deliver technical training programs to employees and customers...",
    requirements:
      "Technical background, public speaking, curriculum development, presentation skills",
    responsibilities:
      "Develop training materials, deliver sessions, assess learning outcomes",
    benefits:
      "Travel opportunities, professional development, flexible schedule",
    company: {
      id: 1,
      name: "Zosh Technologies Pvt Ltd",
      slug: "zosh-technologies-pvt-ltd",
      logoUrl:
        "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
      tagline: "Building scalable microservices & modern web apps",
      industryType: "TECHNOLOGY",
      companySize: "SMALL",
      verified: true,
    },
    employerId: 2,
    category: {
      id: 14,
      name: "Hospitality",
      slug: "hospitality",
      description: "Hotels, restaurants, and tourism",
      iconUrl: "https://example.com/icons/hospitality.png",
      active: true,
      createdAt: "2026-03-02T18:08:23.34877",
    },
    skills: [
      {
        id: 57,
        name: "Communication",
        slug: "communication",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 55,
        name: "Zeplin",
        slug: "zeplin",
        category: "DESIGN",
        active: true,
      },
      {
        id: 59,
        name: "Problem Solving",
        slug: "problem-solving",
        category: "SOFT_SKILL",
        active: true,
      },
      {
        id: 56,
        name: "Canva",
        slug: "canva",
        category: "DESIGN",
        active: true,
      },
    ],
    tags: [
      {
        id: 14,
        name: "Freelance",
        slug: "freelance",
      },
      {
        id: 41,
        name: "Individual Contributor",
        slug: "individual-contributor",
      },
      {
        id: 66,
        name: "Sabbatical",
        slug: "sabbatical",
      },
      {
        id: 4,
        name: "Microservices",
        slug: "microservices",
      },
    ],
    address: "4141 Training Way",
    city: "Chicago",
    state: "IL",
    country: "USA",
    zipCode: "60601",
    minSalary: 80000,
    maxSalary: 110000,
    currency: "USD",
    salaryPeriod: "YEARLY",
    salaryNegotiable: true,
    salaryDisclosed: true,
    jobType: "FULL_TIME",
    workMode: "HYBRID",
    experienceLevel: "MID_LEVEL",
    status: "OPEN",
    openings: 2,
    applicationDeadline: "2024-12-05",
    expiresAt: "2025-01-05",
    active: true,
    viewCount: 24,
    applicationCount: 0,
    createdAt: "2026-03-02T18:59:50.808136",
    updatedAt: "2026-04-08T20:09:37.699191",
    publishedAt: "2026-03-02T19:02:29.870195",
  },
];
