export const saveJobs = [
  {
    id: 1,
    job: {
      id: 1,
      title: "Senior Java Backend Developer",
      description:
        "We are looking for a skilled backend developer to build scalable microservices using Spring Boot and Kafka.",
      requirements:
        "5+ years experience in Java, Spring Boot, Microservices, Docker, Kubernetes, Kafka",
      responsibilities:
        "Design APIs, build microservices, optimize performance, collaborate with frontend team",
      benefits: "Health insurance, flexible working hours, remote work options",
      company: {
        id: 1,
        name: "Zosh Technologies Pvt Ltd",
        slug: "zosh-technologies-pvt-ltd",
        logoUrl:
          "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
        tagline: "Building scalable microservices & modern web apps",
        industryType: "TECHNOLOGY",
        companySize: "SMALL",
        verified: true,
      },
      employerId: 2,
      category: {
        id: 1,
        name: "Software Development",
        slug: "software-development",
        description:
          "Jobs related to software engineering, backend, frontend, and full-stack development.",
        iconUrl: "https://cdn.zosh.com/icons/software-development.png",
        active: true,
        createdAt: "2026-02-28T22:44:31.616396",
      },
      skills: [
        {
          id: 1,
          name: "Spring Boot",
          slug: "spring-boot",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 3,
          name: "Fast API",
          slug: "fast-api",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 2,
          name: "React",
          slug: "react",
          category: "FRAMEWORK",
          active: true,
        },
      ],
      tags: [
        {
          id: 5,
          name: "AI/ML",
          slug: "aiml",
        },
        {
          id: 1,
          name: "urgent-hiring",
          slug: "urgent-hiring",
        },
        {
          id: 2,
          name: "visa-sponsored",
          slug: "visa-sponsored",
        },
      ],
      address: "Rajkot IT Park",
      city: "Rajkot",
      state: "Gujarat",
      country: "India",
      zipCode: "360001",
      minSalary: 800000,
      maxSalary: 1800000,
      currency: "INR",
      salaryPeriod: "YEARLY",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "SENIOR_LEVEL",
      status: "OPEN",
      openings: 3,
      applicationDeadline: "2026-03-31",
      expiresAt: "2026-04-15",
      active: true,
      viewCount: 6,
      applicationCount: 0,
      createdAt: "2026-02-28T23:15:37.736102",
      updatedAt: "2026-04-09T14:58:59.236868",
      publishedAt: "2026-03-02T17:41:57.930648",
    },
  },

  {
    id: 2,
    job: {
      id: 3,
      title: "Frontend React Developer",
      description:
        "Join our product team to build beautiful user interfaces for our SaaS platform...",
      requirements:
        "5+ years of React, TypeScript, Redux, modern CSS frameworks",
      responsibilities:
        "Develop new features, optimize performance, collaborate with designers, maintain component library",
      benefits:
        "Flexible hours, learning budget, equity options, home office stipend",
      company: {
        id: 1,
        name: "Zosh Technologies Pvt Ltd",
        slug: "zosh-technologies-pvt-ltd",
        logoUrl:
          "https://cdn.pixabay.com/photo/2020/09/19/23/42/architecture-5585737_1280.jpg",
        tagline: "Building scalable microservices & modern web apps",
        industryType: "TECHNOLOGY",
        companySize: "SMALL",
        verified: true,
      },
      employerId: 2,
      category: {
        id: 3,
        name: "Healthcare",
        slug: "healthcare",
        description: "Medical and healthcare positions",
        iconUrl: "https://example.com/icons/healthcare.png",
        active: true,
        createdAt: "2026-03-02T18:08:23.295085",
      },
      skills: [
        {
          id: 4,
          name: "Java",
          slug: "java",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 64,
          name: "Conflict Resolution",
          slug: "conflict-resolution",
          category: "SOFT_SKILL",
          active: true,
        },
        {
          id: 3,
          name: "Fast API",
          slug: "fast-api",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 12,
          name: "Swift",
          slug: "swift",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
      ],
      tags: [
        {
          id: 14,
          name: "Freelance",
          slug: "freelance",
        },
        {
          id: 2,
          name: "visa-sponsored",
          slug: "visa-sponsored",
        },
        {
          id: 57,
          name: "Equity",
          slug: "equity",
        },
        {
          id: 4,
          name: "Microservices",
          slug: "microservices",
        },
      ],
      address: "456 Innovation Ave",
      city: "Austin",
      state: "TX",
      country: "USA",
      zipCode: "78701",
      minSalary: 110000,
      maxSalary: 145000,
      currency: "USD",
      salaryPeriod: "YEARLY",
      salaryNegotiable: false,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 2,
      applicationDeadline: "2024-11-15",
      expiresAt: "2024-12-15",
      active: true,
      viewCount: 0,
      applicationCount: 0,
      createdAt: "2026-03-02T18:59:49.418109",
      updatedAt: "2026-03-02T19:01:30.66264",
      publishedAt: "2026-03-02T19:01:30.659561",
    },
  },
];
